RTS/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from RTS import views
import notifications.urls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.index, name='index'),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/password/', include('password_reset.urls')),
                  path('administration/', include('administration.urls')),
                  path('faculty/', include('faculty.urls')),
                  path('student/', include('student.urls')),
                  path('meeting/', include('meeting.urls')),
                  path('', include('django_private_chat.urls')),
                  url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path("", views.home, name='home'),
    path('login/', views.loginPage, name="login"),
    path('login_role_select/', views.login_role_select, name="login_role_select"),
    path('logout/', views.logoutUser, name="logout"),
    path('create_faculty/', views.createFaculty, name="create_faculty"),
    path('create_student/', views.createStudent, name="create_student"),
    path('create_admin/', views.createAdmin, name="create_admin"),
    path('faculty/', views.faculty_list_view, name="faculty_list"),
    path('students/', views.student_list_view, name="students_list"),
    path('admins/', views.admin_list_view, name="admins_list"),
    path('users/', views.user_list_view, name="users_list"),
    path('un_active_users/', views.un_active_user_list_view, name="un_active_users_list"),
    path('active_users/', views.active_user_list_view, name="active_users_list"),
    path('change_password/', views.change_password, name="change_password"),
    path('create_student_with_existing_user/<int:id>/', views.createStudentWithExistingUser,
         name="create_student_with_existing_user"),
    path('create_admin_with_existing_user/<int:id>/', views.createAdminWithExistingUser,
         name="create_admin_with_existing_user"),
    path('create_faculty_with_existing_user/<int:id>/', views.createFacultyWithExistingUser,
         name="create_faculty_with_existing_user"),
    path('active_user/<int:id>/', views.active_user, name="active_user"),
    path('un_active_user/<int:id>/', views.un_active_user, name="un_active_user"),
    path('edit_user/<int:id>/', views.edit_user, name="edit_user"),
    path('edit_student/<int:id>/', views.edit_student, name="edit_student"),
    path('edit_faculty/<int:id>/', views.edit_faculty, name="edit_faculty"),
    path('edit_admin/<int:id>/', views.edit_admin, name="edit_admin"),
    path('remove_admin_group/<int:id>/', views.remove_admin_group, name="remove_admin_group"),
    path('remove_faculty_group/<int:id>/', views.remove_faculty_group, name="remove_faculty_group"),
    path('remove_student_group/<int:id>/', views.remove_student_group, name="remove_student_group"),
    path('faculty_profile/<int:id>/', views.faculty_profile, name="faculty_profile"),
    path('faculty_profile_visitor/<int:id>/', views.faculty_profile_visitor, name="faculty_profile_visitor"),
    path('student_profile/<int:id>/', views.student_profile, name="student_profile"),


]

faculty/urls.py
from django.contrib import admin
from django.urls import path
from faculty import views

app_name = 'faculty'

urlpatterns = [
    path("", views.home, name='faculty home'),
    path('all_available_faculty', views.all_available_faculty, name='all_available_faculty'),
    path('available_faculty', views.available_status_on_faculty, name='available_faculty'),
    path('not_avaialable_faculty', views.available_status_off_faculty, name='not_available_faculty'),
    path('search_availability_faculty', views.search_availability_faculty, name='search_availability_faculty'),
    path("faculty_profile/", views.profile, name='profile'),
    path("edit_profile/", views.edit_profile, name='edit profile'),
    path("faculty_availabilty/", views.availability_status, name='availability_status'),
    path("update_availabilty/", views.update_status, name='update_status'),
    path("schedule/", views.schedule_view, name='schedule_view'),
    path("schedule/today", views.today_schedule_view, name='schedule_view_today'),
    path("create_schedule/", views.schedule_create, name='create_schedule'),
    path("update_schedule/<int:id>/", views.schedule_update, name='update_schedule'),
    path("remove_schedule/<int:id>/", views.schedule_remove, name='remove_schedule'),
    path("schedule/chart/", views.schedule_chart_view, name='schedule_chart_view'),
    path('all_available_faculty_view', views.all_available_faculty_sidebar, name='all_available_faculty_sidebar'),
    path('available_faculty_view', views.available_status_on_faculty_sidebar, name='available_faculty_sidebar'),
    path('not_avaialable_faculty_view', views.available_status_off_faculty_sidebar, name='not_available_sidebar'),
    path('search_availability_faculty_view', views.search_availability_faculty_sidebar,
         name='search_availability_sidebar'),
    path('faculty/profile/<int:id>/', views.faculty_profile_visitor,
         name='faculty_profile'),
    path('schedule/chart/id/<int:id>/', views.schedule_chart_view_for_login_user,
         name='schedule_chart_view_for_login'),
    path('schedule/vistor/chart/id/<int:id>/', views.schedule_chart_view_for_visitors,
         name='schedule_chart_view_for_visitors'),

]

meeting/urls.py
from typing import List, Any

from django.contrib import admin
from django.urls import path
from meeting import views

app_name = 'meeting'

urlpatterns = [
    path("send/request/view/<int:id>/", views.send_meeting_request, name='send_request'),
    path("approve/meeting/<int:id>/", views.meeting_approve, name='approve_meeting'),
    path("reschedule/meeting/<int:id>/", views.meeting_reschedule, name='reschedule_meeting'),
    path("message/meeting/<int:id>/", views.meeting_message, name='message_meeting'),
    path("cancel/meeting/<int:id>/", views.meeting_cancel, name='cancel_meeting'),
    path("complete/meeting/<int:id>/", views.meeting_complete, name='complete_meeting'),
    # views
    path("request/faculty/views/", views.meeting_request_view_faculty, name='meeting_request_faculty_view'),
    path("reschdule/faculty/views/", views.meeting_reschedule_view_faculty, name='meeting_reschedule_faculty_view'),
    path("cancelled/faculty/views/", views.meeting_cancelled_view_faculty, name='meeting_cancel_faculty_view'),
    path("approve/faculty/views/", views.meeting_approve_view_faculty, name='meeting_approve_faculty_view'),
    path("complete/faculty/views/", views.meeting_complete_view_faculty, name='meeting_complete_faculty_view'),

    path("request/user/views/", views.meeting_request_view_user, name='meeting_request_user_view'),
    path("reschdule/user/views/", views.meeting_reschedule_view_user, name='meeting_reschedule_user_view'),
    path("cancelled/user/views/", views.meeting_cancelled_view_user, name='meeting_cancel_user_view'),
    path("approve/user/views/", views.meeting_approve_view_user, name='meeting_approve_user_view'),
    path("complete/user/views/", views.meeting_complete_view_user, name='meeting_complete_user_view'),

    # detail
    path("detail/meeting/view/<int:id>", views.meeting_detail_view_faculty, name='meeting_detail_faculty_view'),
    # detail
    path("detail/meeting/rview/<int:id>", views.meeting_detail_view_requester, name='meeting_detail_requester_view'),
]

accounts/models.py
import os

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
def content_file_faculty(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.first_name, instance.user.id, ext)
    return os.path.join('faculty_profile_pic', filename)


def content_file_student(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.first_name, instance.user.id, ext)
    return os.path.join('student_profile_pic', filename)


def content_file_admin(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.first_name, instance.user.id, ext)
    return os.path.join('admin_profile_pic', filename)


class Faculty(models.Model):
    gender_choice = (
        (None, ' --- Select Gender --- '),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    first_name = models.CharField(max_length=50, )
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    room_location = models.TextField(max_length=255)
    position = models.CharField(max_length=255, default='Lecturer')
    profile_pic = models.ImageField(upload_to=content_file_faculty, blank=True, null=True)
    gender = models.CharField(max_length=2, choices=gender_choice)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Student(models.Model):
    gender_choice = (
        (None, ' --- Select Gender --- '),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    student_id = models.CharField(max_length=30)
    profile_pic = models.ImageField(upload_to=content_file_student, null=True, blank=True)
    gender = models.CharField(max_length=2, choices=gender_choice)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Admin(models.Model):
    gender_choice = (
        (None, ' --- Select Gender --- '),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to=content_file_admin, null=True, blank=True)
    gender = models.CharField(max_length=2, choices=gender_choice)

    def __str__(self):
        return self.first_name + " " + self.last_name

faculty/models.py
from django.db import models
from accounts.models import Faculty
from . import myFields
from django.utils.translation import ugettext as _
from datetime import datetime, date
from django.utils.timesince import timesince


# Create your models here.
class FacultyAvailability(models.Model):
    faculty = models.OneToOneField(Faculty, on_delete=models.CASCADE)
    availability = models.BooleanField(default=False)
    availabilityMsg = models.TextField(blank=True, default="Not Available")

    def __str__(self):
        return f'{self.faculty.first_name}  {self.availability}'


class ScheduleType(models.Model):
    type = models.CharField(max_length=30)
    type_description = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.type} '


class Schedule(models.Model):
    WEEKDAYS = [
        (None, ' --- Select Day --- '),
        (1, _(u"Monday")),
        (2, _(u"Tuesday")),
        (3, _(u"Wednesday")),
        (4, _(u"Thursday")),
        (5, _(u"Friday")),
        (6, _(u"Saturday")),
        (7, _(u"Sunday")),
    ]
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    start_time = models.TimeField()
    end_time = models.TimeField()
    day = models.IntegerField(
        choices=WEEKDAYS)
    schedule_type = models.ForeignKey(ScheduleType, on_delete=models.CASCADE)

    def get_time_diff(self):
        delta = datetime.combine(date.today(), self.end_time) - datetime.combine(date.today(), self.start_time)
        delta_minutes = (delta.days * 24 * 60 + delta.seconds) / 60
        if delta.days < 0:
            delta_minutes *= -1
        return delta_minutes

    def __str__(self):
        return f'{self.faculty.first_name}  {self.get_day_display()} start {self.start_time} end {self.end_time} '

faculty/forms.py
from django import forms
from django.core.exceptions import ValidationError

from faculty.models import *
from faculty.queries import is_valid_schedule_time
from faculty.functions import get_time_diff


class FacultyAvailabilityForm(forms.ModelForm):
    class Meta:
        model = FacultyAvailability
        exclude = ['faculty']


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        exclude = ['faculty']

    def __init__(self, *args, **kwargs):
        super(ScheduleForm, self).__init__(*args, **kwargs)
        self.fields['schedule_type'].empty_label = '--- Please Select Type ---'

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data:
            start_time = cleaned_data["start_time"]
            end_time = cleaned_data['end_time']
            min_time = 15  # in minutes
            if get_time_diff(end_time, start_time) < min_time:
                self.add_error('end_time', f'end time should be greater than start time at least {min_time} minutes')
        return cleaned_data

    def add_start_time_clash_error(self):
        self.add_error('start_time', 'start time clash with other schedule time')

    def add_end_time_clash_error(self):
        self.add_error('end_time', 'end time clash with other schedule time')

    def add_in_valid_error(self):
        self.add_error('end_time', 'end time clash with other schedule time')
        self.add_error('start_time', 'start time clash with other schedule time')

templates/faculty/index.html
{% extends 'RTS/base.html' %}
{% block content_block %}
    <div class="row">
        <div class="col-sm-6">
            <!-- TABLE: LATEST ORDERS -->
            <div class="card">
                <div class="card-header border-transparent">
                    <h3 class="card-title">Today Schedule</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table m-0">
                            <thead>
                            <th>Day</th>
                            <th>Timing</th>
                            <th>Type</th>

                            </thead>
                            <tbody class="table m-0">
                            {% if schedule_list %}
                                {% for schedule in schedule_list %}
                                    <tr>
                                        <td>{{ schedule.get_day_display }}</td>
                                        <td>{{ schedule.start_time|time:'h:i A' }}
                                            - {{ schedule.end_time|time:'h:i A' }}</td>
                                        <td>{{ schedule.schedule_type }}</td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="4" class="bg-info text-center text-muted"> Nothing Scheduled Today</td>
                                </tr>
                            {% endif %}
                            </tbody>

                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.card-body -->
                <div class="card-footer clearfix">
                    <a href="{% url 'faculty:schedule_view_today' %}" class="btn btn-sm btn-info float-left">View Today Schedule</a>
                    <a href="{% url 'faculty:schedule_view' %}" class="btn btn-sm btn-secondary float-right">View All
                        Schedule</a>
                </div>
                <!-- /.card-footer -->
            </div>
            <!-- /.card -->
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header border-transparent">
                    <h3 class="card-title">Availability</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <!-- /.card-header -->

                <!-- /.card-body -->
                <div class="card-body">
                    <div class="card bg-light">
                        <div class="card-header text-muted border-bottom-0">
                            {{ faculty_availability.faculty.position | title }}
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-7">
                                    <h2 class="lead">
                                        <b>{{ faculty_availability.faculty.first_name | title }} </b></h2>
                                    <p class="text-muted text-sm">
                                        <b>About: </b> {{ faculty_availability.faculty.bio | title }} </p>
                                    <ul class="ml-4 mb-0 fa-ul text-muted">
                                        <li class="small"><span class="fa-li"><i
                                                class="fas fa-lg fa-building"></i></span>
                                            {{ faculty_availability.faculty.room_location | title }}
                                        </li>
                                        <li class="small"><span class="fa-li"><i
                                                class="fas fa-lg fa-envelope"></i></span> {{ faculty_availability.availabilityMsg }}
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-5 text-center">
                                    <img src="/media/{{ faculty_availability.faculty.profile_pic | default:"common/default_user.png" }}"
                                         alt="user pic"
                                         class="img-circle img-thumbnail {{ faculty_availability.availability|yesno:"bg-success,bg-danger" }}"
                                         style="max-height:128px!important; max-width:128px!important">
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="card-footer clearfix">

                    <a href="{% url 'faculty:availability_status' %}" class="btn btn-sm btn-secondary float-right">Availability Status</a>
                </div>
                <!-- /.card-footer -->
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{ count_meeting_requests }}</h3>

                    <p>Meeting Requests</p>
                </div>
                <div class="icon">
                    <i class="fas fa-handshake"></i>
                </div>
                <a href="{% url 'meeting:meeting_request_faculty_view' %}" class="small-box-footer">More info <i
                        class="fas fa-arrow-alt-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-4 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
                <div class="inner">
                    <h3>{{ count_meeting_approve }}</h3>

                    <p>Meeting Approve</p>
                </div>
                <div class="icon">
                    <i class="fas fa-handshake"></i>
                </div>
                <a href="{% url 'meeting:meeting_reschedule_faculty_view' %}" class="small-box-footer">More info <i
                        class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-4 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>{{ count_meeting_complete }}</h3>

                    <p>Meeting Complete</p>
                </div>
                <div class="icon">
                    <i class="fas fa-user-lock"></i>
                </div>
                <a href="{% url 'meeting:meeting_complete_faculty_view' %}" class="small-box-footer">More info <i
                        class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <!-- ./col -->
        <div class="col-lg-4 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{count_meeting_reschedule }}</h3>

                    <p>Meeting Reschedule</p>
                </div>
                <div class="icon">
                    <i class="fas fa-handshake"></i>
                </div>
                <a href="{% url 'meeting:meeting_request_faculty_view' %}" class="small-box-footer">More info <i
                        class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <!-- ./col -->
        <div class="col-lg-4 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>{{ count_meeting_cancel }}</h3>

                    <p>Meeting Cancel</p>
                </div>
                <div class="icon">
                    <i class="fas fa-handshake"></i>
                </div>
                <a href="{% url 'meeting:meeting_cancel_faculty_view' %}" class="small-box-footer">More info <i
                        class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->



    </div>
{% endblock %}

templates/faculty/schedule_update.html
{% extends "RTS/base.html" %}
{% load static %}
{% block css_block %}

    <link rel="stylesheet" href="{% static "plugins/select2/css/select2.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/daterangepicker/daterangepicker.css" %}">

{% endblock %}
{% block content_block %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="card-warning">

                <div class="card-header">
                    <div class="card-title">{{ card_title }}</div>
                </div>
                <form method="post" action="{% url 'faculty:update_schedule' id %}">
                    <div class="modal-body">


                        {% load widget_tweaks %}
                        {% csrf_token %}

                        {% for hidden_field in form.hidden_fields %}
                            {{ hidden_field }}
                        {% endfor %}
                        <div class="row">

                            <!---  day -->


                            <div class="col-sm-12">
                                <div class="form-group">
                                    {{ form.day.label_tag }}

                                    {% if form.is_bound %}
                                        {% if form.day.errors %}
                                            {% render_field form.day class="form-control is-invalid" %}
                                            {% for error in form.day.errors %}
                                                <div class="invalid-feedback">
                                                    {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% else %}
                                            {% render_field form.day class="form-control is-valid" %}
                                        {% endif %}
                                    {% else %}
                                        {% render_field form.day class="form-control" %}
                                    {% endif %}
                                </div>
                            </div>
                            <!---  Type -->

                            <div class="col-sm-12">
                                <div class="form-group">
                                    {{ form.schedule_type.label_tag }}

                                    {% if form.is_bound %}
                                        {% if form.schedule_type.errors %}
                                            {% render_field form.schedule_type class="form-control is-invalid" %}
                                            {% for error in form.schedule_type.errors %}
                                                <div class="invalid-feedback">
                                                    {{ error }}
                                                </div>
                                            {% endfor %}
                                        {% else %}
                                            {% render_field form.schedule_type class="form-control is-valid" %}
                                        {% endif %}
                                    {% else %}
                                        {% render_field form.schedule_type class="form-control" %}
                                    {% endif %}
                                </div>
                            </div>
                            <!---  start time-->
                            <div class="col-sm-6">
                                <div class="form-group">
                                    {{ form.start_time.label_tag }}
                                    <div class="input-group date" id="timepicker1" data-target-input="nearest">
                                        {% if form.is_bound %}
                                            {% if form.start_time.errors %}
                                                {% render_field form.start_time class="form-control is-invalid datetimepicker-input" data-target="#timepicker1" %}

                                            {% else %}
                                                {% render_field form.start_time class="form-control is-valid datetimepicker-input" data-target="#timepicker1" %}
                                            {% endif %}
                                        {% else %}
                                            {% render_field form.start_time class="form-control datetimepicker-input" data-target="#timepicker1" %}
                                        {% endif %}
                                        <div class="input-group-append" data-target="#timepicker1"
                                             data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="far fa-clock"></i></div>
                                        </div>
                                        {% for error in form.start_time.errors %}
                                            <div class="invalid-feedback">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>

                            <!---  end time-->

                            <div class="col-sm-6">
                                <div class="form-group">
                                    {{ form.end_time.label_tag }}
                                    <div class="input-group date" id="timepicker" data-target-input="nearest">
                                        {% if form.is_bound %}
                                            {% if form.end_time.errors %}
                                                {% render_field form.end_time class="form-control is-invalid datetimepicker-input" data-target="#timepicker" %}

                                            {% else %}
                                                {% render_field form.end_time class="form-control is-valid datetimepicker-input" data-target="#timepicker" %}
                                            {% endif %}
                                        {% else %}
                                            {% render_field form.end_time class="form-control datetimepicker-input" data-target="#timepicker" %}
                                        {% endif %}
                                        <div class="input-group-append" data-target="#timepicker"
                                             data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="far fa-clock"></i></div>
                                        </div>
                                        {% for error in form.end_time.errors %}
                                            <div class="invalid-feedback">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>


                        </div>


                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>

                    </div>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

{% block script_block %}

    <script> $('#id_day,#id_schedule_type').select2({
        theme: 'bootstrap4'
    })

    $('#timepicker,#timepicker1').datetimepicker({
        format: 'HH:mm',
        pickDate: false,
        pickSeconds: false,
        pick12HourFormat: false
    })
    </script>
{% endblock %}