RTS/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from RTS import views
import notifications.urls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.index, name='index'),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/password/', include('password_reset.urls')),
                  path('administration/', include('administration.urls')),
                  path('faculty/', include('faculty.urls')),
                  path('student/', include('student.urls')),
                  path('meeting/', include('meeting.urls')),
                  path('', include('django_private_chat.urls')),
                  url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path("", views.home, name='home'),
    path('login/', views.loginPage, name="login"),
    path('login_role_select/', views.login_role_select, name="login_role_select"),
    path('logout/', views.logoutUser, name="logout"),
    path('create_faculty/', views.createFaculty, name="create_faculty"),
    path('create_student/', views.createStudent, name="create_student"),
    path('create_admin/', views.createAdmin, name="create_admin"),
    path('faculty/', views.faculty_list_view, name="faculty_list"),
    path('students/', views.student_list_view, name="students_list"),
    path('admins/', views.admin_list_view, name="admins_list"),
    path('users/', views.user_list_view, name="users_list"),
    path('un_active_users/', views.un_active_user_list_view, name="un_active_users_list"),
    path('active_users/', views.active_user_list_view, name="active_users_list"),
    path('change_password/', views.change_password, name="change_password"),
    path('create_student_with_existing_user/<int:id>/', views.createStudentWithExistingUser,
         name="create_student_with_existing_user"),
    path('create_admin_with_existing_user/<int:id>/', views.createAdminWithExistingUser,
         name="create_admin_with_existing_user"),
    path('create_faculty_with_existing_user/<int:id>/', views.createFacultyWithExistingUser,
         name="create_faculty_with_existing_user"),
    path('active_user/<int:id>/', views.active_user, name="active_user"),
    path('un_active_user/<int:id>/', views.un_active_user, name="un_active_user"),
    path('edit_user/<int:id>/', views.edit_user, name="edit_user"),
    path('edit_student/<int:id>/', views.edit_student, name="edit_student"),
    path('edit_faculty/<int:id>/', views.edit_faculty, name="edit_faculty"),
    path('edit_admin/<int:id>/', views.edit_admin, name="edit_admin"),
    path('remove_admin_group/<int:id>/', views.remove_admin_group, name="remove_admin_group"),
    path('remove_faculty_group/<int:id>/', views.remove_faculty_group, name="remove_faculty_group"),
    path('remove_student_group/<int:id>/', views.remove_student_group, name="remove_student_group"),
    path('faculty_profile/<int:id>/', views.faculty_profile, name="faculty_profile"),
    path('faculty_profile_visitor/<int:id>/', views.faculty_profile_visitor, name="faculty_profile_visitor"),
    path('student_profile/<int:id>/', views.student_profile, name="student_profile"),


]

faculty/urls.py
from django.contrib import admin
from django.urls import path
from faculty import views

app_name = 'faculty'

urlpatterns = [
    path("", views.home, name='faculty home'),
    path('all_available_faculty', views.all_available_faculty, name='all_available_faculty'),
    path('available_faculty', views.available_status_on_faculty, name='available_faculty'),
    path('not_avaialable_faculty', views.available_status_off_faculty, name='not_available_faculty'),
    path('search_availability_faculty', views.search_availability_faculty, name='search_availability_faculty'),
    path("faculty_profile/", views.profile, name='profile'),
    path("edit_profile/", views.edit_profile, name='edit profile'),
    path("faculty_availabilty/", views.availability_status, name='availability_status'),
    path("update_availabilty/", views.update_status, name='update_status'),
    path("schedule/", views.schedule_view, name='schedule_view'),
    path("schedule/today", views.today_schedule_view, name='schedule_view_today'),
    path("create_schedule/", views.schedule_create, name='create_schedule'),
    path("update_schedule/<int:id>/", views.schedule_update, name='update_schedule'),
    path("remove_schedule/<int:id>/", views.schedule_remove, name='remove_schedule'),
    path("schedule/chart/", views.schedule_chart_view, name='schedule_chart_view'),
    path('all_available_faculty_view', views.all_available_faculty_sidebar, name='all_available_faculty_sidebar'),
    path('available_faculty_view', views.available_status_on_faculty_sidebar, name='available_faculty_sidebar'),
    path('not_avaialable_faculty_view', views.available_status_off_faculty_sidebar, name='not_available_sidebar'),
    path('search_availability_faculty_view', views.search_availability_faculty_sidebar,
         name='search_availability_sidebar'),
    path('faculty/profile/<int:id>/', views.faculty_profile_visitor,
         name='faculty_profile'),
    path('schedule/chart/id/<int:id>/', views.schedule_chart_view_for_login_user,
         name='schedule_chart_view_for_login'),
    path('schedule/vistor/chart/id/<int:id>/', views.schedule_chart_view_for_visitors,
         name='schedule_chart_view_for_visitors'),

]

student/urls.py
from typing import List, Any

from django.contrib import admin
from django.urls import path
from student import views

app_name = 'student'

urlpatterns = [
    path("", views.home, name='student home'),
    path("profile/", views.profile, name='profile'),
    path("edit/profile/", views.edit_profile, name='edit profile'),
    path("profile/visit/<int:id>", views.student_profile_visitor, name='profile visitor'),

]

accounts/models.py
import os

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
def content_file_faculty(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.first_name, instance.user.id, ext)
    return os.path.join('faculty_profile_pic', filename)


def content_file_student(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.first_name, instance.user.id, ext)
    return os.path.join('student_profile_pic', filename)


def content_file_admin(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.first_name, instance.user.id, ext)
    return os.path.join('admin_profile_pic', filename)


class Faculty(models.Model):
    gender_choice = (
        (None, ' --- Select Gender --- '),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    first_name = models.CharField(max_length=50, )
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    room_location = models.TextField(max_length=255)
    position = models.CharField(max_length=255, default='Lecturer')
    profile_pic = models.ImageField(upload_to=content_file_faculty, blank=True, null=True)
    gender = models.CharField(max_length=2, choices=gender_choice)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Student(models.Model):
    gender_choice = (
        (None, ' --- Select Gender --- '),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    student_id = models.CharField(max_length=30)
    profile_pic = models.ImageField(upload_to=content_file_student, null=True, blank=True)
    gender = models.CharField(max_length=2, choices=gender_choice)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Admin(models.Model):
    gender_choice = (
        (None, ' --- Select Gender --- '),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to=content_file_admin, null=True, blank=True)
    gender = models.CharField(max_length=2, choices=gender_choice)

    def __str__(self):
        return self.first_name + " " + self.last_name

faculty/models.py
from django.db import models
from accounts.models import Faculty
from . import myFields
from django.utils.translation import ugettext as _
from datetime import datetime, date
from django.utils.timesince import timesince


# Create your models here.
class FacultyAvailability(models.Model):
    faculty = models.OneToOneField(Faculty, on_delete=models.CASCADE)
    availability = models.BooleanField(default=False)
    availabilityMsg = models.TextField(blank=True, default="Not Available")

    def __str__(self):
        return f'{self.faculty.first_name}  {self.availability}'


class ScheduleType(models.Model):
    type = models.CharField(max_length=30)
    type_description = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.type} '


class Schedule(models.Model):
    WEEKDAYS = [
        (None, ' --- Select Day --- '),
        (1, _(u"Monday")),
        (2, _(u"Tuesday")),
        (3, _(u"Wednesday")),
        (4, _(u"Thursday")),
        (5, _(u"Friday")),
        (6, _(u"Saturday")),
        (7, _(u"Sunday")),
    ]
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    start_time = models.TimeField()
    end_time = models.TimeField()
    day = models.IntegerField(
        choices=WEEKDAYS)
    schedule_type = models.ForeignKey(ScheduleType, on_delete=models.CASCADE)

    def get_time_diff(self):
        delta = datetime.combine(date.today(), self.end_time) - datetime.combine(date.today(), self.start_time)
        delta_minutes = (delta.days * 24 * 60 + delta.seconds) / 60
        if delta.days < 0:
            delta_minutes *= -1
        return delta_minutes

    def __str__(self):
        return f'{self.faculty.first_name}  {self.get_day_display()} start {self.start_time} end {self.end_time} '

accounts/forms.py
from django import forms
from accounts.models import *
from accounts.queries import *


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data["email"]
        if self.instance.pk is None:  # insert
            if is_email_already_exist(email):
                self.add_error('email', 'email already exist')
        else:
            if is_email_already_exist_id(email, self.instance.pk):
                self.add_error('email', 'email already exist')

        return cleaned_data


class FacultyForm(forms.ModelForm):
    class Meta:
        model = Faculty
        exclude = ['user']


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ['user']


class AdminForm(forms.ModelForm):
    class Meta:
        model = Admin
        exclude = ['user']

faculty/forms.py
from django import forms
from django.core.exceptions import ValidationError

from faculty.models import *
from faculty.queries import is_valid_schedule_time
from faculty.functions import get_time_diff


class FacultyAvailabilityForm(forms.ModelForm):
    class Meta:
        model = FacultyAvailability
        exclude = ['faculty']


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        exclude = ['faculty']

    def __init__(self, *args, **kwargs):
        super(ScheduleForm, self).__init__(*args, **kwargs)
        self.fields['schedule_type'].empty_label = '--- Please Select Type ---'

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data:
            start_time = cleaned_data["start_time"]
            end_time = cleaned_data['end_time']
            min_time = 15  # in minutes
            if get_time_diff(end_time, start_time) < min_time:
                self.add_error('end_time', f'end time should be greater than start time at least {min_time} minutes')
        return cleaned_data

    def add_start_time_clash_error(self):
        self.add_error('start_time', 'start time clash with other schedule time')

    def add_end_time_clash_error(self):
        self.add_error('end_time', 'end time clash with other schedule time')

    def add_in_valid_error(self):
        self.add_error('end_time', 'end time clash with other schedule time')
        self.add_error('start_time', 'start time clash with other schedule time')

student/forms.py
from django import forms
from accounts.models import *
from accounts.queries import *


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ['user', 'student_id']

student/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from RTS.decorators import allowed_users
from student.forms import StudentForm
from accounts.forms import Student
from student.queries import dashboard


# Create your views here.

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['student'])
def home(request):
    context = dict(page_title='Student-Dashboard', h1_title='Student Dashboard', url='dashboard',
                   student_home='active')
    context.update(dashboard(request.user.student))

    return render(request, 'student/index.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['student'])
def profile(request):
    student = request.user.student
    context = dict(page_title='Student-Profile', h1_title='Student Profile', url='student profile', student=student,
                   student_my_profile_li='active', my_account_ul='menu-open')
    return render(request, 'student/profile.html', context)


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['student'])
def edit_profile(request):
    student = request.user.student
    if request.method == "GET":
        form = StudentForm(instance=student)
        context = dict(page_title='Administration-Profile Edit', h1_title='Edit Profile', url='editadmin',
                       card_title="Account Information", form=form,
                       student_my_edit_profile_li='active', my_account_ul='menu-open')
        return render(request, 'student/profile_form.html', context)
    else:
        updated = False
        form = StudentForm(data=request.POST, instance=student, files=request.FILES)
        if form.is_valid():
            admin = form.save()
            updated = True
        if updated:
            messages.success(request, 'Account updated  Successfully')
            return redirect('student:profile')
        else:
            messages.error(request, 'Invalid Information.Check the  Wrong Information')
            context = dict(page_title='Student-Profile Edit', h1_title='Edit Profile', url='editprofile',
                           card_title="Account Information", form=form,
                           student_my_edit_profile_li='active', my_account_ul='menu-open')
            return render(request, 'student/profile_form.html', context)


@login_required(login_url='accounts:login')
def student_profile_visitor(request, id=0):
    if id <= 0:
        messages.error(request, 'Student Not found against this id')
        return redirect('accounts:home')
    else:
        try:
            student: Student = Student.objects.get(pk=id)
        except Student.DoesNotExist:
            messages.error(request, 'Student Not found against this id')
            return redirect('index')
        context = dict(page_title='Student-Student Profile', h1_title='Faculty Profile', url='Student Profile',
                       card_title="Account Information",
                       student=student)
    return render(request, 'student/student_profile_visitor.html', context)

templates/accounts/student_list.html
{% extends "RTS/base.html" %}
{% load static %}
{% load my_tags %}
{% block css_block %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static "plugins/datatables-bs4/css/dataTables.bootstrap4.css" %}">
    <style>
        .scrollable-menu {
            height: auto;
            max-height: 150px;
            overflow-x: hidden;
        }

        div.dataTables_scrollBody.dropdown-visible {
            overflow: visible !important;
        }
    </style>

{% endblock %}
{% block content_block %}
    <div class="row">
    <div class="col-12">
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">{{ card_title }}</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="tb" class="table text-nowrap table-striped table-hover table-responsive-sm overflow-auto">
            <thead>
            <tr>
                <th>Profile Pic</th>
                <th>Name</th>
                <th>User Name</th>
                <th>email</th>
                <th>Groups</th>
                <th>Account Status</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            {% if student_list %}
                {% for student in student_list %}
                    <tr>
                        <td>
                            <div class="col-md-4">
                                {% if student.profile_pic %}
                                    <img src="/media/{{ student.profile_pic }}" alt="User Avatar"
                                         class="img-size-50 mr-4 img-circle">
                                {% else %}
                                    <img src="/media/common/default_user.png" alt="User Avatar"
                                         class="img-size-50 mr-4 img-circle">
                                {% endif %}
                            </div>
                        </td>
                        <td>


                            {{ student.first_name }} {{ student.last_name }}
                            <br>
                            {{ student.student_id }}

                        </td>
                        <td>{{ student.user.username }}</td>
                        <td>{{ student.user.email }}</td>
                        <td>
                            <ol>{% for group in student.user.groups.all %}
                                <li>
                                    {{ group }}
                                </li>
                            {% endfor %}
                            </ol>
                        </td>
                        {% if student.user.is_active %}

                            <td>Active</td>
                        {% else %}
                            <td>In Active</td>
                        {% endif %}

                        <td>
                            <div class="input-group-prepend">
                                <button type="button" data-boundary="viewport" class="btn btn-default dropdown-toggle"
                                        data-toggle="dropdown">
                                    Action
                                </button>
                                <div class="dropdown-menu scrollable-menu">
                                    {% if not student.user.is_active %}
                                        <form method="post"
                                              action="{% url 'accounts:active_user' student.user.id %}?next_page={{ next_page }}">
                                            {% csrf_token %}
                                            <button class="dropdown-item" type="submit">Active User</button>
                                        </form>
                                    {% else %}
                                        <form method="post"
                                              action="{% url 'accounts:un_active_user' student.user.id %}?next_page={{ next_page }}">
                                            {% csrf_token %}
                                            <button class="dropdown-item" type="submit">Un Active User</button>
                                        </form>
                                    {% endif %}

                                    <a class="dropdown-item"
                                       href="{% url 'accounts:edit_user' student.user.id %}?next_page={{ next_page }}">Edit
                                        User</a>
                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item" href="{% url 'accounts:edit_student' student.id %}">Edit
                                        Student</a>
                                    {% if student.user|has_group:"student" %}
                                        <form method="post"
                                              action="{% url 'accounts:remove_student_group' student.user.id %}?next_page={{ next_page }}">
                                            {% csrf_token %}
                                            <button class="dropdown-item" type="submit">Remove Student Group
                                            </button>
                                        </form>


                                    {% else %}
                                        <a class="dropdown-item"
                                           href="{% url 'accounts:create_student_with_existing_user' student.user.id %}?next_page={{ next_page }}">Add
                                            Student</a>
                                    {% endif %}
                                    <a class="dropdown-item"
                                       href="{% url 'accounts:student_profile' student.id %}">
                                        Student Profile</a>
                                </div>
                            </div>
                        </td>


                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="7" class="text-center text-info"> No Record Found</td>
                </tr>
            {% endif %}

            </tbody>
        </table>

    </div>

{% endblock %}


{% block script_block %}
    <script>
        $(function () {
            $('#tb').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "scrollX": false,
            });
        });
        $('#tb').on('show.bs.dropdown', function () {
            $('.dataTables_scrollBody').addClass('dropdown-visible');
        })
            .on('hide.bs.dropdown', function () {
                $('.dataTables_scrollBody').removeClass('dropdown-visible');
            });
    </script>

{% endblock %}

templates/accounts/user_list.html
{% extends "RTS/base.html" %}
{% load static %}
{% load my_tags %}
{% block css_block %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static "plugins/datatables-bs4/css/dataTables.bootstrap4.css" %}">
    <style>
        .scrollable-menu {
            height: auto;
            max-height: 150px;
            overflow-x: hidden;
        }

        div.dataTables_scrollBody.dropdown-visible {
            overflow: visible !important;
        }
    </style>

{% endblock %}
{% block content_block %}
    <div class="row">
    <div class="col-12">
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">{{ card_title }}</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="tb" class="table text-nowrap table-striped table-hover table-responsive-sm overflow-auto">
            <thead>
            <tr>
                <th>User Name</th>
                <th>email</th>
                <th>Groups</th>
                <th>Account Status</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            {% if user_list %}
                {% for user in user_list %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        <td>
                            <ol>{% for group in user.groups.all %}
                                <li>
                                    {{ group }}
                                </li>
                            {% endfor %}
                            </ol>
                        </td>
                        {% if user.is_active %}

                            <td>Active</td>
                        {% else %}
                            <td>In Active</td>
                        {% endif %}

                        <td>
                            <div class="input-group-prepend">
                                <button type="button" data-boundary="viewport" class="btn btn-default dropdown-toggle"
                                        data-toggle="dropdown">
                                    Action
                                </button>
                                <div class="dropdown-menu scrollable-menu">
                                    {% if not user.is_active %}
                                        <form method="post"
                                              action="{% url 'accounts:active_user' user.id %}?next_page={{ next_page }}">
                                            {% csrf_token %}
                                            <button class="dropdown-item" type="submit">Active User</button>
                                        </form>
                                    {% else %}
                                        <form method="post"
                                              action="{% url 'accounts:un_active_user' user.id %}?next_page={{ next_page }}">
                                            {% csrf_token %}
                                            <button class="dropdown-item" type="submit">Un Active User</button>
                                        </form>
                                    {% endif %}

                                    <a class="dropdown-item"
                                       href="{% url 'accounts:edit_user' user.id%}?next_page={{ next_page }}">Edit
                                        User</a>
                                    <div class="dropdown-divider"></div>

                                    {% if user.admin %}
                                        {% if user|has_group:"admin" %}
                                            <form method="post"
                                                  action="{% url 'accounts:remove_admin_group' user.id%}?next_page={{ next_page }}">
                                                {% csrf_token %}
                                                <button class="dropdown-item" type="submit">Remove Admin Group</button>
                                            </form>

                                        {% else %}
                                            <a class="dropdown-item"
                                               href="{% url 'accounts:create_admin_with_existing_user' user.id%}?next_page={{ next_page }}">Add
                                                Admin</a>
                                        {% endif %}
                                    {% else %}
                                        {% if user|has_group:"faculty" %}
                                            <form method="post"
                                                  action="{% url 'accounts:remove_faculty_group' user.id%}?next_page={{ next_page }}">
                                                {% csrf_token %}
                                                <button class="dropdown-item" type="submit">Remove Faculty Group
                                                </button>
                                            </form>
                                        {% else %}

                                            <a class="dropdown-item"
                                               href="{% url 'accounts:create_faculty_with_existing_user' user.id %}?next_page={{ next_page }}">Add
                                                Faculty</a>
                                        {% endif %}
                                        <div class="dropdown-divider"></div>
                                        {% if user|has_group:"student" %}
                                            <form method="post"
                                                  action="{% url 'accounts:remove_student_group' user.id %}?next_page={{ next_page }}">
                                                {% csrf_token %}
                                                <button class="dropdown-item" type="submit">Remove Student Group
                                                </button>
                                            </form>


                                        {% else %}
                                            <a class="dropdown-item"
                                               href="{% url 'accounts:create_student_with_existing_user' user.id %}?next_page={{ next_page }}">Add
                                                Student</a>
                                        {% endif %}


                                    {% endif %}
                                </div>


                            </div>
                        </td>

                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="7" class="text-center text-info"> No Record Found</td>
                </tr>
            {% endif %}

            </tbody>
        </table>

    </div>

{% endblock %}


{% block script_block %}
    <script>
        $(function () {
            $('#tb').DataTable({

                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "scrollX": true,
            });
        });

        $('#tb').on('show.bs.dropdown', function () {
            $('.dataTables_scrollBody').addClass('dropdown-visible');
        })
            .on('hide.bs.dropdown', function () {
                $('.dataTables_scrollBody').removeClass('dropdown-visible');
            });
    </script>

{% endblock %}