RTS/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from RTS import views
import notifications.urls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.index, name='index'),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/password/', include('password_reset.urls')),
                  path('administration/', include('administration.urls')),
                  path('faculty/', include('faculty.urls')),
                  path('student/', include('student.urls')),
                  path('meeting/', include('meeting.urls')),
                  path('', include('django_private_chat.urls')),
                  url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meeting/urls.py
from typing import List, Any

from django.contrib import admin
from django.urls import path
from meeting import views

app_name = 'meeting'

urlpatterns = [
    path("send/request/view/<int:id>/", views.send_meeting_request, name='send_request'),
    path("approve/meeting/<int:id>/", views.meeting_approve, name='approve_meeting'),
    path("reschedule/meeting/<int:id>/", views.meeting_reschedule, name='reschedule_meeting'),
    path("message/meeting/<int:id>/", views.meeting_message, name='message_meeting'),
    path("cancel/meeting/<int:id>/", views.meeting_cancel, name='cancel_meeting'),
    path("complete/meeting/<int:id>/", views.meeting_complete, name='complete_meeting'),
    # views
    path("request/faculty/views/", views.meeting_request_view_faculty, name='meeting_request_faculty_view'),
    path("reschdule/faculty/views/", views.meeting_reschedule_view_faculty, name='meeting_reschedule_faculty_view'),
    path("cancelled/faculty/views/", views.meeting_cancelled_view_faculty, name='meeting_cancel_faculty_view'),
    path("approve/faculty/views/", views.meeting_approve_view_faculty, name='meeting_approve_faculty_view'),
    path("complete/faculty/views/", views.meeting_complete_view_faculty, name='meeting_complete_faculty_view'),

    path("request/user/views/", views.meeting_request_view_user, name='meeting_request_user_view'),
    path("reschdule/user/views/", views.meeting_reschedule_view_user, name='meeting_reschedule_user_view'),
    path("cancelled/user/views/", views.meeting_cancelled_view_user, name='meeting_cancel_user_view'),
    path("approve/user/views/", views.meeting_approve_view_user, name='meeting_approve_user_view'),
    path("complete/user/views/", views.meeting_complete_view_user, name='meeting_complete_user_view'),

    # detail
    path("detail/meeting/view/<int:id>", views.meeting_detail_view_faculty, name='meeting_detail_faculty_view'),
    # detail
    path("detail/meeting/rview/<int:id>", views.meeting_detail_view_requester, name='meeting_detail_requester_view'),
]

accounts/models.py
import os

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
def content_file_faculty(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.first_name, instance.user.id, ext)
    return os.path.join('faculty_profile_pic', filename)


def content_file_student(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.first_name, instance.user.id, ext)
    return os.path.join('student_profile_pic', filename)


def content_file_admin(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.first_name, instance.user.id, ext)
    return os.path.join('admin_profile_pic', filename)


class Faculty(models.Model):
    gender_choice = (
        (None, ' --- Select Gender --- '),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    first_name = models.CharField(max_length=50, )
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    room_location = models.TextField(max_length=255)
    position = models.CharField(max_length=255, default='Lecturer')
    profile_pic = models.ImageField(upload_to=content_file_faculty, blank=True, null=True)
    gender = models.CharField(max_length=2, choices=gender_choice)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Student(models.Model):
    gender_choice = (
        (None, ' --- Select Gender --- '),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    student_id = models.CharField(max_length=30)
    profile_pic = models.ImageField(upload_to=content_file_student, null=True, blank=True)
    gender = models.CharField(max_length=2, choices=gender_choice)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Admin(models.Model):
    gender_choice = (
        (None, ' --- Select Gender --- '),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to=content_file_admin, null=True, blank=True)
    gender = models.CharField(max_length=2, choices=gender_choice)

    def __str__(self):
        return self.first_name + " " + self.last_name

meeting/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from accounts.models import *
from datetime import datetime


# Create your models here.

class Meeting(models.Model):
    status_choice = (
        ('approve', 'Approve'),
        ('cancel', 'Cancel'),
        ('re_scheduled', 'Re Schedule'),
        ('complete', 'Complete'),
        ('request', 'Request'),
        ('system_cancel', 'Canceled by System')
    )
    requester_type_choice = (
        ('s', 'Student'),
        ('f', 'faculty'),
    )
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    date = models.DateField()
    start_time = models.TimeField()
    finish_time = models.TimeField(null=True)
    meeting_duration = models.IntegerField(validators=[MinValueValidator(10), MaxValueValidator(180)],
                                           verbose_name='Duration (minute)')
    meeting_status = models.CharField(max_length=20, choices=status_choice)
    initiate_time = models.DateTimeField(default=datetime.now, blank=True)
    requester_type = models.CharField(max_length=2, choices=requester_type_choice)

    def __str__(self):
        return f'{self.id} {self.faculty} {self.date} {self.start_time} {self.meeting_duration} {self.finish_time} ' \
               f'{self.meeting_status} '


class Meeting_Detail(models.Model):
    status_choice = (
        ('message', 'message'),
        ('approve', 'Approve'),
        ('cancel', 'Cancel'),
        ('re_scheduled', 'Re Schedule'),
        ('complete', 'Complete'),
        ('request', 'Request'),
        ('system_cancel', 'Canceled by System')
    )
    type_choice = (
        ('r', 'requester'),
        ('f', 'faculty'),
        ('s', 'System')
    )
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    start_time = models.TimeField(null=True, blank=True)
    text = models.CharField(max_length=255, null=True, blank=True)
    meeting_duration = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(10)])
    meeting_status = models.CharField(max_length=20, choices=status_choice)
    initiate_time = models.DateTimeField(default=datetime.now, blank=True, null=True)
    owner_type = models.CharField(max_length=2, choices=type_choice)

    def __str__(self):
        return f" {self.meeting} {self.initiate_time}  {self.initiate_time} {self.owner_type}"

meeting/forms.py
from django import forms
from meeting.models import *
from meeting.functions import *


class Meeting_Form(forms.ModelForm):
    class Meta:
        model = Meeting
        exclude = ['user', 'faculty', 'meeting_status', 'requester_type', 'initiate_time', 'finish_time']

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data:
            t_date = cleaned_data["date"]
            t_days = 0
            if not is_future_date(t_date, t_days):
                self.add_error('date', f'meeting should be in future with {t_days} day')
        return cleaned_data

    def add_date_error(self):
        self.add_error('date', f'meeting date day and time clash with faculty schedule')

    def add_time__error(self):
        self.add_error('start_time', f'meeting time clash with faculty schedule')

    def add_duration__error(self):
        self.add_error('meeting_duration', f'meeting end time clash with faculty schedule')

    def add_invalid_meeting_faculty(self):
        self.add_error('date', f'meeting date clash with faculty meetings')
        self.add_error('start_time', f'meeting time clash with faculty meetings')
        self.add_error('meeting_duration', f'meeting end time clash with faculty meetings')

    def add_invalid_meeting_user(self):
        self.add_error('date', f'meeting date clash with your meetings')
        self.add_error('start_time', f'meeting time clash with your meetings')
        self.add_error('meeting_duration', f'meeting end time clash with yours meetings')


class Meeting_Reschedule_Form(forms.ModelForm):
    class Meta:
        model = Meeting
        exclude = ['user', 'faculty', 'meeting_status', 'requester_type', 'initiate_time', 'finish_time', 'subject']

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data:
            t_date = cleaned_data["date"]
            t_days = 0
            if not is_future_date(t_date, t_days):
                self.add_error('date', f'meeting should be in future with {t_days} day')
        return cleaned_data

    def add_date_error(self):
        self.add_error('date', f'meeting date day and time clash with faculty schedule')

    def add_time__error(self):
        self.add_error('start_time', f'meeting time clash with faculty schedule')

    def add_duration__error(self):
        self.add_error('meeting_duration', f'meeting end time clash with faculty schedule')

    def add_invalid_meeting_faculty(self):
        self.add_error('date', f'meeting date clash with faculty meetings')
        self.add_error('start_time', f'meeting time clash with faculty meetings')
        self.add_error('meeting_duration', f'meeting end time clash with faculty meetings')

    def add_invalid_meeting_user(self):
        self.add_error('date', f'meeting date clash with your meetings')
        self.add_error('start_time', f'meeting time clash with your meetings')
        self.add_error('meeting_duration', f'meeting end time clash with yours meetings')


class Meeting_Detail_Text_Form(forms.ModelForm):
    text = forms.CharField(max_length=255, required=True)

    class Meta:
        model = Meeting_Detail
        fields = ['text']
        labels = {
            "text": "Embed"
        }


class Meeting_Detail_Text_Form_Empty_Allow(forms.ModelForm):
    class Meta:
        model = Meeting_Detail
        fields = ['text']
        labels = {'text': "Message"}


class Meeting_Detail_Form(forms.ModelForm):
    class Meta:
        model = Meeting_Detail
        fields = ['date', 'start_time', 'meeting_duration']

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data:
            t_date = cleaned_data["date"]
            t_days = 0
            if not is_future_date(t_date, t_days):
                self.add_error('date', f'meeting should be in future with {t_days} day')
        return cleaned_data

    def add_date_error(self):
        self.add_error('date', f'meeting date day and time clash with faculty schedule')

    def add_time__error(self):
        self.add_error('start_time', f'meeting time clash with faculty schedule')

    def add_duration__error(self):
        self.add_error('meeting_duration', f'meeting end time clash with faculty schedule')

    def add_invalid_meeting_faculty(self):
        self.add_error('date', f'meeting date clash with faculty meetings')
        self.add_error('start_time', f'meeting time clash with faculty meetings')
        self.add_error('meeting_duration', f'meeting end time clash with faculty meetings')

    def add_invalid_meeting_user(self):
        self.add_error('date', f'meeting date clash with your meetings')
        self.add_error('start_time', f'meeting time clash with your meetings')
        self.add_error('meeting_duration', f'meeting end time clash with yours meetings')

templates/meeting/meeting_approve_view_faculty.html
{% extends "RTS/base.html" %}
{% load static %}
{% load my_tags %}
{% block css_block %}

    <!-- DataTables -->
    <link rel="stylesheet" href="{% static "plugins/datatables-bs4/css/dataTables.bootstrap4.css" %}">
    <style>
        .scrollable-menu {
            height: auto;
            max-height: 150px;
            overflow-x: hidden;
        }

        div.dataTables_scrollBody.dropdown-visible {
            overflow: visible !important;
        }
    </style>

{% endblock %}
{% load humanize %}
{% block content_block %}
    <div class="row">
    <div class="col-12">
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">{{ card_title }}</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body ">
        <table id="tb" class="table table-hover text-nowrap table-responsive overflow-auto">
            <thead>
            <tr>
                <th>Profile Pic</th>
                <th>Name</th>
                <th>Meeting Subject</th>
                <th>Meeting Date</th>
                <th>Meeting Time</th>
                <th>Requested Time</th>
                <th>Meeting Status</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            {% if meeting_list %}
                {% for meeting in meeting_list %}
                    <tr>
                        {% if meeting.requester_type == 'f' %}

                            <td>

                                <div class="col-md-4">
                                    {% if meeting.user.faculty.profile_pic %}
                                        <img src="/media/{{ meeting.user.faculty.profile_pic }}" alt="User Avatar"
                                             class="img-size-50 mr-4 img-circle">
                                    {% else %}
                                        <img src="/media/common/default_user.png" alt="User Avatar"
                                             class="img-size-50 mr-4 img-circle">
                                    {% endif %}
                                </div>
                            </td>
                            <td>


                                {{ meeting.user.faculty.first_name }} {{ meeting.user.faculty.last_name }}
                                <br>
                                {{ meeting.get_requester_type_display }}


                            </td>
                        {% else %}
                            <td>

                                <div class="col-md-4">
                                    {% if meeting.user.student.profile_pic %}
                                        <img src="/media/{{ meeting.user.student.profile_pic }}" alt="User Avatar"
                                             class="img-size-50 mr-4 img-circle">
                                    {% else %}
                                        <img src="/media/common/default_user.png" alt="User Avatar"
                                             class="img-size-50 mr-4 img-circle">
                                    {% endif %}
                                </div>
                            </td>
                            <td>

                                <div class="small text-justify">
                                    {{ meeting.user.student.first_name }}
                                    <br>
                                    <small>{{ meeting.get_requester_type_display }}</small>
                                </div>

                            </td>
                        {% endif %}
                        <td>{{ meeting.subject }}</td>
                        <td>{{ meeting.date }}</td>
                        <td>
                            <div class="text-*-center small">{{ meeting.start_time |time:'h:i A' }}-{{ meeting.finish_time |time:'h:i A' }}</div>
                        </td>
                        <td>{{ meeting.initiate_time | naturaltime }}</td>
                        <td>{{ meeting.get_meeting_status_display }}</td>

                        <td>
                            <div class="input-group-prepend">
                                <button type="button" data-boundary="viewport" class="btn btn-default dropdown-toggle"
                                        data-toggle="dropdown">
                                    Action
                                </button>
                                <div class="dropdown-menu scrollable-menu">


                                    <a class="dropdown-item"
                                       href="{% url 'meeting:meeting_detail_faculty_view' meeting.id %}">View Detail</a>
                                    <div class="dropdown-divider"></div>
                                    <form method="post"
                                          action="{% url 'meeting:complete_meeting' meeting.id %}?next_page={{ next_page }}">
                                        {% csrf_token %}
                                        <button class="dropdown-item" type="submit">Meeting Complete</button>
                                    </form>
                                    <form method="post"
                                          action="{% url 'meeting:approve_meeting' meeting.id %}?next_page={{ next_page }}">
                                        {% csrf_token %}
                                        <button class="dropdown-item" type="submit">Cancel</button>
                                    </form>

                                    <a class="dropdown-item"
                                       href="{% url 'meeting:reschedule_meeting' meeting.id %}?next_page={{ next_page }}">
                                        Re Schedule
                                    </a>
                                </div>
                            </div>
                        </td>

                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="8" class="text-info text-center"> No Record Found</td>
                </tr>
            {% endif %}

            </tbody>
        </table>

    </div>
{% endblock %}


{% block script_block %}
    <script>
        $(function () {
            $('#tb').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "scrollX": false,
            });
        });
        $('#tb').on('show.bs.dropdown', function () {
            $('.dataTables_scrollBody').addClass('dropdown-visible');
        })
            .on('hide.bs.dropdown', function () {
                $('.dataTables_scrollBody').removeClass('dropdown-visible');
            });
    </script>

{% endblock %}

templates/meeting/meeting_cancelled_view_faculty.html
{% extends "RTS/base.html" %}
{% load static %}
{% load my_tags %}
{% block css_block %}

    <!-- DataTables -->
    <link rel="stylesheet" href="{% static "plugins/datatables-bs4/css/dataTables.bootstrap4.css" %}">
    <style>
        .scrollable-menu {
            height: auto;
            max-height: 150px;
            overflow-x: hidden;
        }

        div.dataTables_scrollBody.dropdown-visible {
            overflow: visible !important;
        }
    </style>

{% endblock %}
{% load humanize %}
{% block content_block %}
    <div class="row">
    <div class="col-12">
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">{{ card_title }}</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body ">
        <table id="tb" class="table table-hover text-nowrap table-responsive overflow-auto">
            <thead>
            <tr>
                <th>Profile Pic</th>
                <th>Name</th>
                <th>Meeting Subject</th>
                <th>Meeting Date</th>
                <th>Meeting Time</th>
                <th>Requested Time</th>
                <th>Meeting Status</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            {% if meeting_list %}
                {% for meeting in meeting_list %}
                    <tr>
                        {% if meeting.requester_type == 'f' %}

                            <td>

                                <div class="col-md-4">
                                    {% if meeting.user.faculty.profile_pic %}
                                        <img src="/media/{{ meeting.user.faculty.profile_pic }}" alt="User Avatar"
                                             class="img-size-50 mr-4 img-circle">
                                    {% else %}
                                        <img src="/media/common/default_user.png" alt="User Avatar"
                                             class="img-size-50 mr-4 img-circle">
                                    {% endif %}
                                </div>
                            </td>
                            <td>


                                {{ meeting.user.faculty.first_name }} {{ meeting.user.faculty.last_name }}
                                <br>
                                {{ meeting.get_requester_type_display }}


                            </td>
                        {% else %}
                            <td>

                                <div class="col-md-4">
                                    {% if meeting.user.student.profile_pic %}
                                        <img src="/media/{{ meeting.user.student.profile_pic }}" alt="User Avatar"
                                             class="img-size-50 mr-4 img-circle">
                                    {% else %}
                                        <img src="/media/common/default_user.png" alt="User Avatar"
                                             class="img-size-50 mr-4 img-circle">
                                    {% endif %}
                                </div>
                            </td>
                            <td>

                                <div class="small text-justify">
                                    {{ meeting.user.student.first_name }}
                                    <br>
                                    <small>{{ meeting.get_requester_type_display }}</small>
                                </div>

                            </td>
                        {% endif %}
                        <td>{{ meeting.subject }}</td>
                        <td>{{ meeting.date }}</td>
                        <td>
                            <div class="text-*-center small">{{ meeting.start_time |time:'h:i A' }}-{{ meeting.finish_time |time:'h:i A' }}</div>
                        </td>
                        <td>{{ meeting.initiate_time | naturaltime }}</td>
                        <td>{{ meeting.get_meeting_status_display }}</td>

                        <td>
                            <div class="input-group-prepend">
                                <button type="button" data-boundary="viewport" class="btn btn-default dropdown-toggle"
                                        data-toggle="dropdown">
                                    Action
                                </button>
                                <div class="dropdown-menu scrollable-menu">


                                    <a class="dropdown-item"
                                       href="{% url 'meeting:meeting_detail_faculty_view' meeting.id %}">View Detail</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item"
                                            href="{% url 'meeting:reschedule_meeting' meeting.id %}?next_page={{ next_page }}">
                                        Re Schedule
                                    </a>
                                </div>
                            </div>
                        </td>

                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="9" class="text-info text-center"> No Record Found</td>
                </tr>
            {% endif %}

            </tbody>
        </table>

    </div>
{% endblock %}


{% block script_block %}
    <script>
        $(function () {
            $('#tb').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "scrollX": false,
            });
        });
        $('#tb').on('show.bs.dropdown', function () {
            $('.dataTables_scrollBody').addClass('dropdown-visible');
        })
            .on('hide.bs.dropdown', function () {
                $('.dataTables_scrollBody').removeClass('dropdown-visible');
            });
    </script>

{% endblock %}

templates/meeting/meeting_reschedule_view_user.html
{% extends "RTS/base.html" %}
{% load static %}
{% load my_tags %}
{% block css_block %}

    <!-- DataTables -->
    <link rel="stylesheet" href="{% static "plugins/datatables-bs4/css/dataTables.bootstrap4.css" %}">
    <style>
        .scrollable-menu {
            height: auto;
            max-height: 150px;
            overflow-x: hidden;
        }

        div.dataTables_scrollBody.dropdown-visible {
            overflow: visible !important;
        }
    </style>

{% endblock %}
{% load humanize %}
{% block content_block %}
    <div class="row">
    <div class="col-12">
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">{{ card_title }}</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body ">
        <table id="tb" class="table table-hover text-nowrap table-responsive overflow-auto">
            <thead>
            <tr>
                <th>Profile Pic</th>
                <th>Name</th>
                <th>Meeting Subject</th>
                <th>Meeting Date</th>
                <th>Meeting Time</th>
                <th>Requested Time</th>
                <th>Meeting Status</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            {% if meeting_list %}
                {% for meeting in meeting_list %}
                    <tr>

                        <td>

                            <div class="col-md-4">
                                {% if meeting.faculty.profile_pic %}
                                    <img src="/media/{{ meeting.faculty.profile_pic }}" alt="User Avatar"
                                         class="img-size-50 mr-4 img-circle">
                                {% else %}
                                    <img src="/media/common/default_user.png" alt="User Avatar"
                                         class="img-size-50 mr-4 img-circle">
                                {% endif %}
                            </div>
                        </td>
                        <td>
                            {{ meeting.faculty.first_name }}
                        </td>
                        <td>{{ meeting.subject }}</td>
                        <td>{{ meeting.date }}</td>
                        <td>
                            <div class="text-*-center small">{{ meeting.start_time |time:'h:i A' }}-{{ meeting.finish_time |time:'h:i A' }}</div>
                        </td>
                        <td>{{ meeting.initiate_time | naturaltime }}</td>
                        <td>{{ meeting.get_meeting_status_display }}</td>

                        <td>
                            <div class="input-group-prepend">
                                <button type="button" data-boundary="viewport" class="btn btn-default dropdown-toggle"
                                        data-toggle="dropdown">
                                    Action
                                </button>
                                <div class="dropdown-menu scrollable-menu">


                                    <a class="dropdown-item"
                                       href="{% url 'meeting:meeting_detail_requester_view' meeting.id %}">View
                                        Detail</a>
                                    <form method="post"
                                          action="{% url 'meeting:approve_meeting' meeting.id %}?next_page={{ next_page }}">
                                        {% csrf_token %}
                                        <button class="dropdown-item" type="submit">Approve</button>
                                    </form>
                                    <form method="post"
                                          action="{% url 'meeting:approve_meeting' meeting.id %}?next_page={{ next_page }}">
                                        {% csrf_token %}
                                        <button class="dropdown-item" type="submit">Reject</button>
                                    </form>

                                </div>
                            </div>
                        </td>

                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="9" class="text-info text-center"> No Record Found</td>
                </tr>
            {% endif %}

            </tbody>
        </table>

    </div>
{% endblock %}


{% block script_block %}
    <script>
        $(function () {
            $('#tb').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "scrollX": false,
            });
        });
        $('#tb').on('show.bs.dropdown', function () {
            $('.dataTables_scrollBody').addClass('dropdown-visible');
        })
            .on('hide.bs.dropdown', function () {
                $('.dataTables_scrollBody').removeClass('dropdown-visible');
            });
    </script>

{% endblock %}