RTS/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from RTS import views
import notifications.urls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.index, name='index'),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/password/', include('password_reset.urls')),
                  path('administration/', include('administration.urls')),
                  path('faculty/', include('faculty.urls')),
                  path('student/', include('student.urls')),
                  path('meeting/', include('meeting.urls')),
                  path('', include('django_private_chat.urls')),
                  url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path("", views.home, name='home'),
    path('login/', views.loginPage, name="login"),
    path('login_role_select/', views.login_role_select, name="login_role_select"),
    path('logout/', views.logoutUser, name="logout"),
    path('create_faculty/', views.createFaculty, name="create_faculty"),
    path('create_student/', views.createStudent, name="create_student"),
    path('create_admin/', views.createAdmin, name="create_admin"),
    path('faculty/', views.faculty_list_view, name="faculty_list"),
    path('students/', views.student_list_view, name="students_list"),
    path('admins/', views.admin_list_view, name="admins_list"),
    path('users/', views.user_list_view, name="users_list"),
    path('un_active_users/', views.un_active_user_list_view, name="un_active_users_list"),
    path('active_users/', views.active_user_list_view, name="active_users_list"),
    path('change_password/', views.change_password, name="change_password"),
    path('create_student_with_existing_user/<int:id>/', views.createStudentWithExistingUser,
         name="create_student_with_existing_user"),
    path('create_admin_with_existing_user/<int:id>/', views.createAdminWithExistingUser,
         name="create_admin_with_existing_user"),
    path('create_faculty_with_existing_user/<int:id>/', views.createFacultyWithExistingUser,
         name="create_faculty_with_existing_user"),
    path('active_user/<int:id>/', views.active_user, name="active_user"),
    path('un_active_user/<int:id>/', views.un_active_user, name="un_active_user"),
    path('edit_user/<int:id>/', views.edit_user, name="edit_user"),
    path('edit_student/<int:id>/', views.edit_student, name="edit_student"),
    path('edit_faculty/<int:id>/', views.edit_faculty, name="edit_faculty"),
    path('edit_admin/<int:id>/', views.edit_admin, name="edit_admin"),
    path('remove_admin_group/<int:id>/', views.remove_admin_group, name="remove_admin_group"),
    path('remove_faculty_group/<int:id>/', views.remove_faculty_group, name="remove_faculty_group"),
    path('remove_student_group/<int:id>/', views.remove_student_group, name="remove_student_group"),
    path('faculty_profile/<int:id>/', views.faculty_profile, name="faculty_profile"),
    path('faculty_profile_visitor/<int:id>/', views.faculty_profile_visitor, name="faculty_profile_visitor"),
    path('student_profile/<int:id>/', views.student_profile, name="student_profile"),


]

administration/urls.py
from django.contrib import admin
from django.urls import path
from administration import views

app_name = 'administration'

urlpatterns = [
    path("", views.home, name='home'),
    path("admin_profile/", views.profile, name='profile'),
    path("edit_profile/", views.edit_profile, name='edit profile'),

]

faculty/urls.py
from django.contrib import admin
from django.urls import path
from faculty import views

app_name = 'faculty'

urlpatterns = [
    path("", views.home, name='faculty home'),
    path('all_available_faculty', views.all_available_faculty, name='all_available_faculty'),
    path('available_faculty', views.available_status_on_faculty, name='available_faculty'),
    path('not_avaialable_faculty', views.available_status_off_faculty, name='not_available_faculty'),
    path('search_availability_faculty', views.search_availability_faculty, name='search_availability_faculty'),
    path("faculty_profile/", views.profile, name='profile'),
    path("edit_profile/", views.edit_profile, name='edit profile'),
    path("faculty_availabilty/", views.availability_status, name='availability_status'),
    path("update_availabilty/", views.update_status, name='update_status'),
    path("schedule/", views.schedule_view, name='schedule_view'),
    path("schedule/today", views.today_schedule_view, name='schedule_view_today'),
    path("create_schedule/", views.schedule_create, name='create_schedule'),
    path("update_schedule/<int:id>/", views.schedule_update, name='update_schedule'),
    path("remove_schedule/<int:id>/", views.schedule_remove, name='remove_schedule'),
    path("schedule/chart/", views.schedule_chart_view, name='schedule_chart_view'),
    path('all_available_faculty_view', views.all_available_faculty_sidebar, name='all_available_faculty_sidebar'),
    path('available_faculty_view', views.available_status_on_faculty_sidebar, name='available_faculty_sidebar'),
    path('not_avaialable_faculty_view', views.available_status_off_faculty_sidebar, name='not_available_sidebar'),
    path('search_availability_faculty_view', views.search_availability_faculty_sidebar,
         name='search_availability_sidebar'),
    path('faculty/profile/<int:id>/', views.faculty_profile_visitor,
         name='faculty_profile'),
    path('schedule/chart/id/<int:id>/', views.schedule_chart_view_for_login_user,
         name='schedule_chart_view_for_login'),
    path('schedule/vistor/chart/id/<int:id>/', views.schedule_chart_view_for_visitors,
         name='schedule_chart_view_for_visitors'),

]

meeting/urls.py
from typing import List, Any

from django.contrib import admin
from django.urls import path
from meeting import views

app_name = 'meeting'

urlpatterns = [
    path("send/request/view/<int:id>/", views.send_meeting_request, name='send_request'),
    path("approve/meeting/<int:id>/", views.meeting_approve, name='approve_meeting'),
    path("reschedule/meeting/<int:id>/", views.meeting_reschedule, name='reschedule_meeting'),
    path("message/meeting/<int:id>/", views.meeting_message, name='message_meeting'),
    path("cancel/meeting/<int:id>/", views.meeting_cancel, name='cancel_meeting'),
    path("complete/meeting/<int:id>/", views.meeting_complete, name='complete_meeting'),
    # views
    path("request/faculty/views/", views.meeting_request_view_faculty, name='meeting_request_faculty_view'),
    path("reschdule/faculty/views/", views.meeting_reschedule_view_faculty, name='meeting_reschedule_faculty_view'),
    path("cancelled/faculty/views/", views.meeting_cancelled_view_faculty, name='meeting_cancel_faculty_view'),
    path("approve/faculty/views/", views.meeting_approve_view_faculty, name='meeting_approve_faculty_view'),
    path("complete/faculty/views/", views.meeting_complete_view_faculty, name='meeting_complete_faculty_view'),

    path("request/user/views/", views.meeting_request_view_user, name='meeting_request_user_view'),
    path("reschdule/user/views/", views.meeting_reschedule_view_user, name='meeting_reschedule_user_view'),
    path("cancelled/user/views/", views.meeting_cancelled_view_user, name='meeting_cancel_user_view'),
    path("approve/user/views/", views.meeting_approve_view_user, name='meeting_approve_user_view'),
    path("complete/user/views/", views.meeting_complete_view_user, name='meeting_complete_user_view'),

    # detail
    path("detail/meeting/view/<int:id>", views.meeting_detail_view_faculty, name='meeting_detail_faculty_view'),
    # detail
    path("detail/meeting/rview/<int:id>", views.meeting_detail_view_requester, name='meeting_detail_requester_view'),
]

RTS/views.py
from django.http import HttpResponse

from django.shortcuts import render
from faculty.models import FacultyAvailability
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def index(request):
    faculty_availability = FacultyAvailability.objects.all().order_by('-availability')
    page = request.GET.get('page', 1)

    paginator = Paginator(faculty_availability, 10)
    try:
        faculty_availability = paginator.page(page)
    except PageNotAnInteger:
        faculty_availability = paginator.page(1)
    except EmptyPage:
        faculty_availability = paginator.page(paginator.num_pages)
    context = dict(page_title='Home', h1_title='Home', url='home', faculty_availability=faculty_availability)
    return render(request, 'RTS/index.html', context)

templates/RTS/base_top_navbar.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Resource Tracking System | {{ page_title |  title }}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block css_block %}
    {% endblock %}
    <!-- summernote -->
    <link rel="stylesheet" href="{% static "plugins/summernote/summernote-bs4.css" %}">


    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">

    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet"
          href="{% static "plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
    <!-- Google Font: Source Sans Pro -->
    <link href=https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">

    <!-- iCheck -->
    <link rel="stylesheet" href="{% static "plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static "plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}">


</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">

    <!-- Navbar -->
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <div class="container">
            <a href="{% url 'index' %}" class="navbar-brand">
                <img src=" {% static "Rts_logo.png" %}" alt="RTS Logo"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Resource Tracking System</span>
            </a>

            <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                <!-- Left navbar links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'index' %}" class="nav-link">Home</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'accounts:home' %}" class="nav-link">Dash Board</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
                        </li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false" class="nav-link dropdown-toggle">Faculty Availability</a>
                        <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                            <li><a href="{% url 'faculty:all_available_faculty' %}" class="dropdown-item">All </a></li>
                            <li><a href="{% url 'faculty:available_faculty' %}" class="dropdown-item">Available </a>
                            </li>
                            <li><a href="{% url 'faculty:not_available_faculty' %}" class="dropdown-item">Not
                                Available</a></li>


                        </ul>
                    </li>

                </ul>


                <!-- SEARCH FORM -->
                <form class="form-inline ml-0 ml-md-3" method="get"
                      action="{% url 'faculty:search_availability_faculty' %}">
                    <div class="input-group input-group-sm">
                        <input name="query" class="form-control  form-control-navbar" type="search"
                               placeholder="Search Faculty"
                               aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>

            <!-- Right navbar links -->
            <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                {% if request.user.is_authenticated %}
                    <!-- Profile -->
                    <li class="nav-item dropdown">
                        <a class="nav-link" data-toggle="dropdown" href="#">
                            <i class="far fas fa-user-circle fa-fw"></i>
                            <span class="badge badge-primary navbar-badge"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">
            {% if request.session.login_role == 'admin' %}
                <div>


                <img src="/media/{{ request.user.admin.profile_pic| default:"common/default_user.png" }}"
                     class="img-circle mx-auto d-block img-thumbnail"
                     style="max-height:100px; max-width: 100px " alt="User Image">

           </div>

                <p>
                  {{ request.user.admin.first_name }} - {{ request.session.login_role | title }}<br>
                  <small>Member since {{ request.user.date_joined | date:"d M Y" }}</small>
                </p>
                </span>
                <div class="dropdown-divider"></div>
                <div class="dropdown-item dropdown-footer">
                    <div class="btn-group-justified">

                        {% if request.user.groups.count > 1 %}
                            <a href="{% url 'accounts:login_role_select' %}" class="btn btn-default btn-flat">Switch
                                Role</a>
                        {% endif %}
                        <a href="{% url 'administration:profile' %}" class="btn btn-default btn-flat">Profile</a>
                        <a href="{% url 'accounts:logout' %}"
                           class="btn btn-default btn-flat">Sign out</a>


                    </div>


                </div>
            {% elif request.session.login_role == 'student' %}
                <div>


                    <img src="/media/{{ request.user.student.profile_pic | default:"common/default_user.png" }}"
                         class="img-circle mx-auto d-block img-thumbnail"
                         style="max-height:100px; max-width: 100px " alt="User Image">


                </div>

                <p>
                    {{ request.user.student.first_name }} - {{ request.session.login_role | title }}<br>
                    <small>Member since {{ request.user.date_joined | date:"d M Y" }}</small>
                </p>
                </span>
                <div class="dropdown-divider"></div>
                <div class="dropdown-item dropdown-footer">
                    <div class="btn-group-justified">

                        {% if request.user.groups.count > 1 %}

                            <a href="{% url 'accounts:login_role_select' %}" class="btn btn-default btn-flat">Switch
                                Role</a>

                        {% endif %}

                        <a href="Profile.html" class="btn btn-default btn-flat">Profile</a>


                        <a href="{% url 'accounts:logout' %}"
                           class="btn btn-default btn-flat">Sign out</a>


                    </div>


                </div>
            {% elif request.session.login_role == 'faculty' %}
                <div>

                    <img src="/media/{{ request.user.faculty.profile_pic | default:"common/default_user.png" }}"
                         class="img-circle mx-auto d-block img-thumbnail"
                         style="max-height:100px; max-width: 100px " alt="User Image">


                </div>

                <p>
                    {{ request.user.faculty.first_name }} - {{ request.session.login_role | title }}<br>
                    <small>Member since {{ request.user.date_joined | date:"d M Y" }}</small>
                </p>
                </span>
                <div class="dropdown-divider"></div>
                <div class="dropdown-item dropdown-footer">
                    <div class="btn-group-justified">

                        {% if request.user.groups.count > 1 %}

                            <a href="{% url 'accounts:login_role_select' %}" class="btn btn-default btn-flat">Switch
                                Role</a>

                        {% endif %}

                        <a href="Profile.html" class="btn btn-default btn-flat">Profile</a>


                        <a href="{% url 'accounts:logout' %}"
                           class="btn btn-default btn-flat">Sign out</a>


                    </div>
                </div>
            {% endif %}

                        </div>
                    </li>
                {% endif %}


            </ul>
        </div>
    </nav>
    <!-- /.navbar -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ h1_title  |  title }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">{{ url }}</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                {{ message | lower}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            {% block content_block %}
            {% endblock %}

            <!-- /.row -->
        </section>
        <!-- /.content -->


    </div>
    <!-- /.content-wrapper -->


    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- Select2 -->
<script src="{% static "plugins/select2/js/select2.full.min.js" %}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{% static "plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js" %}"></script>

<!-- DataTables -->
<script src="{% static "plugins/datatables/jquery.dataTables.js" %}"></script>
<script src="{% static "plugins/datatables-bs4/js/dataTables.bootstrap4.js" %}"></script>
<!-- InputMask -->
<script src="{% static "plugins/moment/moment.min.js" %}"></script>
<script src="{% static "plugins/inputmask/min/jquery.inputmask.bundle.min.js" %}"></script>
<!-- date-range-picker -->
<script src="{% static "plugins/daterangepicker/daterangepicker.js" %}"></script>

<script src="{% static "plugins/sweetalert2/sweetalert2.min.js" %}"></script>
<!-- bootstrap color picker -->
<script src="{% static "plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Bootstrap Switch -->
<script src="{% static "plugins/bootstrap-switch/js/bootstrap-switch.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "dist/js/adminlte.min.js" %}"></script>

<!-- Page script -->



{% block script_block %}
{% endblock %}

</body>
</html>

templates/RTS/error_403.html
{% extends 'RTS/base.html' %}

{% block content_block %}
    <!-- Main content -->
    <section class="content">
        <div class="error-page">
            <h2 class="headline text-warning"> 403</h2>

            <div class="error-content">
                <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! 403 FORBIDDEN</h3>

                <p>
                    We could not find the page you were looking for.
                    Meanwhile, you may <a href="{% url 'accounts:home' %}">return to dashboard</a>
                    {% if role_switch %}
                        or you may <a href="{% url 'accounts:login_role_select' %}">switch role</a>
                    {% endif %}
                    {% if not request.user.admin %}or
                        try using the search form for faculty.
                    {% endif %}
                </p>
                {% if not request.user.admin %}

                    <form class="search-form" method="get" action="{% url 'faculty:search_availability_sidebar' %}">
                        <div class="input-group">
                            <input type="text" name="query" class="form-control" placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-warning"><i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                        <!-- /.input-group -->
                    </form>
                {% endif %}
            </div>
            <!-- /.error-content -->
        </div>
        <!-- /.error-page -->
    </section>
{% endblock %}